name: "Security Scan"
description: "Comprehensive security scanning including audit and sensitive data detection"

inputs:
  scan-type:
    description: "Type of scan to perform (audit, sensitive-data, or both)"
    required: false
    default: "both"

outputs:
  audit-status:
    description: "Status of dependency audit"
    value: ${{ steps.audit.outputs.status }}

  sensitive-data-status:
    description: "Status of sensitive data scan"
    value: ${{ steps.sensitive.outputs.status }}

runs:
  using: "composite"
  steps:
    - name: Run dependency audit
      if: inputs.scan-type == 'audit' || inputs.scan-type == 'both'
      id: audit
      shell: bash
      run: |
        echo "Running security audit..."
        if bun audit --audit-level low; then
          echo "✅ No security vulnerabilities found"
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "❌ Security vulnerabilities detected"
          echo "status=failure" >> $GITHUB_OUTPUT
          exit 1
        fi

    - name: Scan for sensitive data
      if: inputs.scan-type == 'sensitive-data' || inputs.scan-type == 'both'
      id: sensitive
      shell: bash
      run: |
        echo "Scanning for sensitive data patterns..."

        # Define patterns to search for
        PATTERNS=(
          "password\s*[:=]\s*['\"][^'\"]*['\"]"
          "api[_-]?key\s*[:=]\s*['\"][^'\"]*['\"]"
          "secret\s*[:=]\s*['\"][^'\"]*['\"]"
          "token\s*[:=]\s*['\"][^'\"]*['\"]"
          "private[_-]?key\s*[:=]"
          "-----BEGIN\s+(RSA\s+)?PRIVATE\s+KEY-----"
        )

        FOUND_ISSUES=false

        for pattern in "${PATTERNS[@]}"; do
          if grep -r -i -E "$pattern" . \
            --exclude-dir=node_modules \
            --exclude-dir=.git \
            --exclude-dir=build \
            --exclude-dir=dist \
            --exclude="*.log" \
            --exclude="*.lockb" 2>/dev/null; then
            echo "❌ Sensitive data pattern found: $pattern"
            FOUND_ISSUES=true
          fi
        done

        if [ "$FOUND_ISSUES" = "true" ]; then
          echo "status=failure" >> $GITHUB_OUTPUT
          echo "❌ Sensitive data patterns detected in codebase"
          exit 1
        else
          echo "status=success" >> $GITHUB_OUTPUT
          echo "✅ No sensitive data patterns found"
        fi
